---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: dev
spec:
  encryptedData:
    REDIS_PASSWORD: AgBHR4+o2PlU2UxhLPH25BUP3N3hMtG7qTsdc1a2fxIvL/Dm6jlaZVSRq5X4vVx7q7i+cKHXrmvlog/eVBc2Jqy9beRvsbocB0CYRUF5FRXhL5amJKa3KFGVYVu3g/qlfU7mISMrksMsHJpZobJF5rCUS5wy2SpWKOfV4P28mfC+GLjVBXLyQx9ib231jvwa+HiuVa/sqM2UHl6EXPjUygy/YmPZrGI98eXQ6gaDuYtbpRiQse0By7FHqmb9rz+eQo+5r66FtJq7/USnVuKsOHldQ+Wo0aXcjgfscUiuChMq1Dg+hlU4zqsIPFvxN8ldCDkTZJjGcCufZIzjQumcNQoG+UlevDTOok4WkWROBxqlxv+F8C7ePp1LYRe++w3RZqF7vPCHE2TzFXCkQ3wYL96uuLNb4KHnkaio36bRG3lZJQMwJcxhC2Mv6vARqpgAeBF0lg1EmBTdJmHyoFqaAHRhGhXm1wq8gxQ4z0dWHS0Y3fma1Qeyfj4CTejTIa2OVMWlkhWhys3TKuYa0p10Dyj0thBX/5iBy4+5vUvfQ/vJI9b2vYLN906vhmq89aV9vWxtr0HIfoOueREgDVWGYK6BFD8H66W/3mYcPYJgDXep0I978SWPlS+GYGbSIVZNiz1181xSV8YIO9Vom0hsJaWvOvTuZDnh/o4aYT1icxMoDpsAG+Lxe/IhHn2sR9x0aGHi/WmSZS6gw9nK
  template:
    metadata:
      name: app-secret
      namespace: dev
    type: Opaque
