---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: dev
spec:
  encryptedData:
    REDIS_PASSWORD: AgC5C9bD8iWOgYLXn4p4olBQpdE2LQjvq/+rXuB39ZUjL4WGDpkAHtt6CHE/zHeNvGcO1lyp7DWnzJ8jlCgu7lUJLMUNP72LbRwvdI/AJCNBFY7MUysIUVMsb/uRw7mgKhxecDLK3ft3O0vXCs1ulshzkxRz4Ti1QoTbmdNCrGFJnJnPTuxUdCM2IEWVwXJB/RqgGA1kJw/xRPln1DVJqzNP/kFPTWTQ0oPeUVMN9oEWKrmYbtK6U2ZRQlKiSk2ISSZQ1GCdU2hMNcZi7BYsm+eugSM+UDhZePZMiz4dMuFw4KKtA9ndEoTROq60kw+a7Lx8myo9xTbOHpILT2DCY8zce/C51e/Vl3GFbGZ8TXQs7Fc3V0gCMzqv7j1wrF1TvvizrWpxe6NVxdvH0jzxA5gZccaCA+gt5QwgZtcaA6Ui98dB9yP7onVBoLJ8IlIMprkRvtMURdONmNhLm6HVPgMb21Xsz8jNzXHUM3kvyPl+fe4sMBqeP7g3WlLWWR0pmWKGsV+Me06UIQt5kbps5Psq/xIUqUFK7Ju7M/AXfj2+WYJF7Xh0ZjAYenFNa6H+aTGPx2mB6fJPn3E/F42lxprMTgQUADupn4Sb6Ys2Wvhk7Z7cobchS0PLYcgbd8l0SAQgFyIqjyJzP5oqug7aVtfrPnPd9WdY7vDsn6KtS9vgp5zWpGkak+Usw4lK9Mth3vRuUiSjdAwQqGL/
  template:
    metadata:
      name: app-secret
      namespace: dev
    type: Opaque
