---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: dev
spec:
  encryptedData:
    REDIS_PASSWORD: AgBATpbTphMSJdXVLLwu1sXa/vwHZESxZ/+HcUIAiDPDvzr1W8Q+mojY0qaQDpYB9THkTrpS2tZL/H1DVHIExeHULG2V3/xfJiycOdU8uG4n557cQ6sd/9IHSU2BksBgB3edav++A4axb48y6Gy57u+psQudYRrjQ1p4frEomcJG7WSkZdDifadCC8BmbV+tQW4ekQ8h2qLDLAFfLorgdutSECCw0gGDstGtvcGILfcNGrgxD0Rgp3oaI1N0uVuyJSRFFhdIg2FBIBuO+kRM93kk1pLvzSZ36NiGsfVeJhsDwufsdwe4uH+qnw6IPQRwTVQO9HyKWSVSxneDA2y0aOOpY3QxkmwkqVhrrsZk17KtCDtdThunAQXwcX/4BC2PdDlJrBrsOYyKI4sLJT9UaMzDTit3BRyLkGEXxkpVRWooSQRCB+AmfNmOHkncX0he2LAX15tAocXbMY2VLDsgsgwDeuole3jqfp8eLG9ue7xv3p+79tuku/ZGNxefiGk5VMFXTP5ksBcUVy7j9JZFwnJtysJd6BMveDxo45fcGIDZxHUPV5xOoqR6vttfyqx9ZybzWw0+Y9aKMLIA3r85OY9b6RBF/0bYNeNR6pmvvhfDQXzcoX5EAyMnHLDmhv4f/Nw8EJ7WO7pDo4e+FxLtAN23TzvVbfh4ZJWhYMErjZiAcXd0c+1QzIVH5jUzEMiGqqNl/jEd8bQLkEfa
  template:
    metadata:
      name: app-secret
      namespace: dev
    type: Opaque
