apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- namespace.yaml
- ../../base/common
- ../../base/api
- ../../base/frontend
- ../../base/redis
- ../../base/network-policies
- app-sealed-secret.yaml

commonLabels:
  environment: dev

  # API customizations
  
  # Frontend customizations
  
  # API HPA customizations
  
  # Frontend HPA customizations
  
  # ConfigMap environment patch
patches:
- patch: |-
    - op: add
      path: /spec/replicas
      value: 1
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "200m"
  target:
    kind: Deployment
    name: api
- patch: |-
    - op: add
      path: /spec/replicas
      value: 1
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "200m"
  target:
    kind: Deployment
    name: frontend
- patch: |-
    - op: add
      path: /spec/minReplicas
      value: 1
    - op: add
      path: /spec/maxReplicas
      value: 3
  target:
    kind: HorizontalPodAutoscaler
    name: api-hpa
- patch: |-
    - op: add
      path: /spec/minReplicas
      value: 1
    - op: add
      path: /spec/maxReplicas
      value: 3
  target:
    kind: HorizontalPodAutoscaler
    name: frontend-hpa
- patch: |-
    - op: replace
      path: /data/APP_ENV
      value: "development"
    - op: replace
      path: /data/LOG_LEVEL
      value: "debug"
  target:
    kind: ConfigMap
    name: app-config
images:
- name: theyemiii/task-api
  newName: theyemiii/task-api
  newTag: 07706367e29660aede19b30c22edf242f70c4efa
- name: theyemiii/task-frontend
  newName: theyemiii/task-frontend
  newTag: 2445c8fc6b3c94c3e3878070906dc5a091f00439
