---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-config
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yml: AgCXSpzou8fl5MtEHDVrA7e6GV1OwsP1EeCf8jIR8LBQIcn84AmwP+1R7SFL6KgwJNNpcCtosX27jiMp0Fda3359eY31BK8JKetuNJYjcC4UhylYkP1ZGD7a4wxRDDZENjDwzPBfQflBh8rJ3sZcWA8yqG5M5PzX/RSaVIP6FtgAhfWfiZA6Ie+ZakelZqWgs/aqtp/Q79GvLYd3Q5UNyI8xWgVVnWP1igqesiuJ/kgxdEiyFpesOgID9GavKXrXw0SPLHuPQrCcY2j5vJ9aQUOdh5RtJ3PW7Y3eE4p7m5glyITDVwvk9A3EH40noqWzepBNpIevD5Kly2pkbDbE8IiNfVGf3NM5/cXti+Q7qG9krnZ+BPDpUZXnAHeJSfPhGS4vzxx9cBiN5+1m+xScO834cFJ4VLRt6SYGwkF9b80LNda4KUy1eyPe+rKbiil5mjWBAeoU8YN3VDXmDeoPiA0Q133vkPcmkY1K27P9rd1fMnujc5D6pgS9JEUx7UTHh11F3p1OETbgEm+KvQJpqJnV0ISi277ADz5HUC0QSB8Hmn/lQ5XlFXlRSqn8YNe6U0I8owfIj3gIUz1sajqxPPJSl7AdjNTQljwONsD6GWYMWlGDDD8x59ikiB/XPzCur3kSB0iTwDguDHeFpe9ChykI4Osf59uATG0yBVPnr+GeYKWmfE+lQOHMxBintqlM15zn2hmk2rmPVcYp9perj8/xE2inbXbob3KN1TDeWzFjnIyWbShQ0owb4N9OUIjupQ+P25oosDtwJirKFP7jn8Fn2fEpwrcZrJZSRgnp4GuAB7QQ6TE=
  template:
    metadata:
      name: alertmanager-config
      namespace: monitoring
    type: Opaque
