---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCfYK9kROFi10S1LPemIa4rTsGCD3fdy57DM9EtDsxEnougZaarbNmZDcOtiQGoYvAATfH0zTrcg9wPfgQHjgtLXJgRMpwZ1U5xhxXlCdaK6QivvCtSD5GLgXMkvQgKHKdKsXXRrtucY+NknMxZNOyX0H9OwfHHS1V9hkuoboRQmccEQG6hgLWbzMYsZUBbwaK75Pzb6hP532T2YTkuvBu2YeEbepiTEA7x1aRdbQ+7FVBZNFNaxDKzdUIDl7bH4Q68R2Mn5uV9sTGhJQEnG2FxDncqq8ZiuQm/D/kUUDq8GgQaBElj5EXAZRIIn5hjolN8pii2eC58IVemfz3G7SVQuMd/nlsT69GwCLMZmaKzzNLxC37R3Vk4J8jvCaK1ETuyqj+LRs3w5SyMgrsbUBNAT/a7jvNpVJWAh3ZzqQAfrHiljKtTjtskLQ1/uxJaZ0ebP+q2bE5GBBnueNcY6kQB4pn++qSG2LGYvZav/x0ZVHgfQReGN65wM5VHa3lbiVHGTd7iT0vvs+JT25YOYHxaqILUy6zyTg80Bc8kZFPdlcqwzPD4rhqoSZJXwXc0dR+QJpPyBUAB6lmGPiSjGTKuBSg3TltLYSSXjfQ+sCvfNwHoJkiDCVIP/GIBvNuRZN3HcG/AmLpxoCbjQ2cETSdMrsdd6Pjc27CJj+2zukQ5iaxZ/WeVPCVcO52eLKgc7BpgZwk0wjs8TBVB
  template:
    metadata:
      name: grafana-secret
      namespace: monitoring
