---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCEJvha6BrAswb7FUobAC5Ya4NEP9Ntlkn34lqfijUYfDjkIXzzjEy7BwgqhWpV05bx/H/9A4ykZvKEMW5uCsRbG/ingJ7FrR4B5RPatP0ffYmWUKIohyTJfCP5D5sXIm+OaQICD6X9z02ES7lppyYeG3H2IvyDlOmPbslcyiKYUp0d4U745Xetyxq3i04Lw3bPf7ugYXlVFoPAXHpyhVV3lawmBruhnEdmkNi8PyraByoPPdjOJsuzWpjuiVIMIRJXmInFvywB/hIE4qQDa/NKSrWGWnprKd5cEuZc66sv5Y9JsNomUGxRzPxdo+tXE8LvLXycxcJnD8uFvonVjrTr0ucf7OBKfrNJ1DWGCjVOH3wECSMBHeT1OIBIc2LfZXJ8mq7Ym3WzG9akoq277ZEes7dO3JFNDJvQq8NSPxbf5klk7Tq1UdQA/pQWrRfnSGPh78L0VZdIaAhMdPsM50O/40rfUjtYXN4pZpTM67r24dA43FTVn2TF6LdBir1BKKFKEobfptKOlNu05yPphpvvUEit14Osuw7IJiKjqgQ7BhFtamtqQ/iu7w+eqiawx/JJkTaBOE/GVARUJgW3HJSjlvEqPl7SwaNOwitaUKVEk31OL/iuIcg1n6zMEuxruUBC1jT33kacobiCCKgzXkC0o3HJwJOgvTfgeH+KLrrGV6+sshl4F5vjnWogeQkPECbKt84wrGukek7N
  template:
    metadata:
      name: grafana-secret
      namespace: monitoring
    type: Opaque
