---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAmskj6XfILnrfTmuVkRfc+xUimAKehzSb8JyK6RD5grs9lwTKCiRlMFbN8tFA004nPWgSxTFuIs73cPcriuY3jWfiimiVT1H95C/0RWdPfeNsMmwgekSrlZyr5D/8bN9Y5cFIxMhUT2gK7uUDQ0i6tNVaRBEE1tyTX4rZcO3jVV87ytLCNG51UjTvo3uifR6QuDSRYib66N7pjDvuZfAXknAop2yrbH2V7T3qEIBZGXmC4RwjzJxtg0ExZheNrL48G0UZYdfXtOQfACE/L3v0gwDRh0y92GPHn+U5FC2i5SZdtc2JedSn8CFUenZaZ7CZWYr2WNVEz6gRdLe4tS5KoIP7bG2mvC5dHMJgi0OmqkSyDBz5d3TSRMtA0GfJduaacm9yCYQvPMwiD2xnB+g412m8oZGka4QhWVRAl3xS2+8m7s1n1wTg5FrBr9XZR0UysMWuUGmU0/fEo+ih2Qeg3ez0DWoyj0/LOuKi184tkutBpWaBSTOuCRGMDD6fRSBwdy9MnfutXBYCXGK1gRb1ymxEyPwdsiWNPzfvZ4v+i3FhB4TztOUmmaP9S4o/YYZ6v6ax8Zr27IbpsLONZD76gLy9IUU0XfltZ8hwNgwJkVON2C/WAc0WKn9yT2xA4XoaI2dBXdEpJ/dkYsoOMAumZ9N0fn2VwOyDzXefBXV7uT+zIHqXrGk4gYVKKL6r1YfwcQ2tYH9fv7Q==
  template:
    metadata:
      name: grafana-secret
      namespace: monitoring
    type: Opaque
