apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: 3.2.6
    helm:
      values: |
        admissionController:
          replicas: 1
        backgroundController:
          replicas: 1
        cleanupController:
          enabled: false
        reportsController:
          replicas: 1
        cleanupJobs:
          admissionReports:
            enabled: false
          clusterAdmissionReports:
            enabled: false
          ephemeralReports:
            enabled: false
          clusterEphemeralReports:
            enabled: false
          updateRequests:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true