apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-probes
  annotations:
    policies.kyverno.io/title: Require Liveness and Readiness Probes
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      All containers must have liveness and readiness probes.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: check-probes
    match:
      any:
      - resources:
          kinds:
          - Deployment
          - StatefulSet
          namespaces:
          - staging
          - prod
    validate:
      message: "Liveness and readiness probes are required"
      pattern:
        spec:
          template:
            spec:
              containers:
              - livenessProbe:
                  "?*": "?*"
                readinessProbe:
                  "?*": "?*"
