---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: prod
spec:
  encryptedData:
    REDIS_PASSWORD: AgBNsvdrHuKIEZvhLQ5W4/iZ0GKAQibkdKAttUI6A6PnZUambX+dn0wb2nwbyAOysXA1CrOqcs+sWYwxMAGcT7qTkj4rAgp6TDNBfvHVD9HB0lpTkjo5h5NtqICqVvRSdILT31SeS5miPRYZ2YT8tx+0EPBMzXZKYA4gBzEr1rSt9LqvMDgbBP2wYQZPjrlrheDoLkTJsy13RHvpmzPR3/bHJj8fd+4P4OK9d96SBOQYIUWiwgNoTHznslUXvcG5IiX3wIMvzNNkh6exvPL/G52aqai1eWWy1pcr5gGbjKCLNatbwxVWa3X/Qp5VTclJ9ydQvxWwiPOssZaTr3+2IrvgNPkX9+ZzOUyQXAdPbgfyOAXe0/0ICRrX8TKZn8wf3+AqvU5bcfj8S1tJ9S59HTbCupoaUkeKjJ1cQx/Ef1YhwhLYSCdDdP/sKAizc8JVi7q5mHGWBm5tbrlogdXdDw7vzm9go/2xWeBlcUEtUZtpJ+HyEB05WTsTXP/+w/cOCksYX9zK1jR0wiI/EBkrcz9RM6x1tsTBtt+9CgY7Tjky31VMzZT7/q7qihkFRmoH0PfvJ2JwKhDs9XvxDIwR5+h2hUVSqaWzZAifaQ6gtQyww14qAvfBuW1bYe0NI1x/OztOrKnU+lqStg/6CtuudUIN9FaBQD/xUtmYj1b/K3Y8wCJQz5uc6jSVBV9mRV6IP818AWzXdcT2yKXs
  template:
    metadata:
      name: app-secret
      namespace: prod
    type: Opaque
