---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: prod
spec:
  encryptedData:
    REDIS_PASSWORD: AgCpLgz6ae0id4dEcbo9jPm5AlN7DzMvrnnllFpA8j6FJO2XjYemG90tGSshqeEsALlCUYenOp8+DRMLZbj/xs1v9pQQs+EHbJ7ktq8izxRyld8vpNznGf6a5QZwiV9amys2vGZ7Zyi6JL+mFJedCFuwNvkSCbUWiFy5KW1ZdTZPJ7Xr3J96gWDeLeP4IIkJmof1bwCYG3SegODxJk5K9K/6JC0Ke1jD00LFp1CnWisRAJJoT4eapGiFoXj7lqIRD/BWc1FIHwrWXZjDki2qVFQp7mM55iCOxMFpD7mtFXli3ELOJH8ES9E7+YLAeLM2DdQcACtRC/pVliHyREJFcgF7T83g34xOtO8HdO9UGVSg3ZEanAFcZkhWEPA47RsRqv3nHJ19csIc+6hycD7Z4zzFiRmdx/vpZkg3bmjuhVIo1RRQU6Tr9kkgiWY+rKVArE53DgP0HK8Af6TFCh29bqpTaVqApFSQNTGcysNULo0pBcwuIFzPz5T0ziCQVfO0D46sjkx894m12p28J5R5mTQ0oGSSuns6EYm/sOgc5n3/6qDfFpdRAF8ER6AeCgUKd6QtvluDRcNZ7r+NYD/n68LmRDZC03AE5IRGjObCI2WF10x1r/yQCh6si7pOIgbVY/yubtXXqso2lRKCdg9WSFioUpsZF1VCp21lJwk5pqKNPQAZSAYKfEUI8DmHJjw6hs5WpoGXVq449iag
  template:
    metadata:
      name: app-secret
      namespace: prod
