---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: prod
spec:
  encryptedData:
    REDIS_PASSWORD: AgBobgQZvju7SFD9QoBVI7f9ums1xrD9LgO0MDrkFsiLtMnn9OkuXpmHJ5VPlG3uuMXwPUZV5tHM2YpnFLaMFXdC6xsx9f+jWcQvTurOdnStc3wGEjttRpKtfeb8GP9PXm77Jg8AGrTlm+VsNkl2x5egeAa6N8EToVPU4+lECgIt5bzKg9TlRlVCuV9kVredWO7gNeuupMSTzFu4OTXXRsJAdBHkd9i6ro5+BJzA1Ok8cy7/iAegjKCMgOs60XTOBjhTfIdOJiBQog5xXsIW92UarbI/FyAGxsG5wmgXdlFr3haPWx4ddP00VcMwwAnD74lBYAiyiUY72PiDDm5EM9ik/3RShVOhsOL466VWMnoBwSbhKFYvosury/FHCDGxD7tIHm+9zUddMiR79LRqfJgyBhyOsqqSPOzIIJOUUYTtzhQUBlzBlWL0KKBYoWt7Bj/jni3+sDr0QRUP8jInunxxk4yHi81B4WWc4YHubYO3yyb1wpJd0BpbDkgumRi+4WCyT8h9S1rGJs51qJZmStB3MKRVy/KAl+rtaIckllPSAWLiX8+tdtt/8sf9SwvK0tdh85a6+ko0V0emrdbN8rgcF1Z2FxwM3mRe6YhxFuMAm+FKxLMMJdpHayzrTVFDDb9vmkNUgh+PZngzwXnFCeaPJ1hbsM6B1NWPeHUZYwNFjNPlHMR9igGFvY4/iAqS98/ZPX1Fi8Vvo+VI
  template:
    metadata:
      name: app-secret
      namespace: prod
    type: Opaque
