---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: staging
spec:
  encryptedData:
    REDIS_PASSWORD: AgAvFSngEDEl+2Ngvya6KwrAwrwUBxC1uG8m52537By+zhKFJo6k96PmZHISzS6xnM0cEItq1XbwzF/9cFMds9IC8jvG6YG4ts9bxafWRVLQAuNP+dg6bSTLj6VRv6cAQbk5LBcc0wm8xZmB0MXka1QXA04v4v48SsGwKVDgKvLZSH6JrLwSCOzGbCed/aq6Tr6J9jquYWGRx6J3dN8Co4JJxdmKknDTaAwRs83XnsfrHbee/+kMWoBthE4CEJ36z5M6rR7ITOqJYAQkKJx7tUo8pVvmbdvEjXkPHEwDLkpN2wVgYqemgnFmj+Cj9tEhgGckiEwhfUV3ykX3QE/8KX4tTg1bE+1+fCbxBsTsxKNtggvDpSb3iSAsg16icBcm7bYgH7q6zQH0Ljud76VcsXq4e1ZelSFpkm0qCG69yy6wvZwHiNkOySMoeVvaBOpyFslEvEn9uE6UNokcpM8z5J29yQlsBS/iI7GQlkHreKsxaLeBSvVprgFDORhzKiFK47JUIZqUyubV09VR/Iy9Bkpg626gkyWGyXeCanGiz59Fkb0xE3mT/YwpbB4Dn+KL39GBaX9ASKfvqOvZqLOv2sMwjUyhiTZG2ds3tXPLo7e437HuqBHpRqlPe1lKpfqnQZzIJVgK6CZnQLDVfxNA6mDw8IyUbuI3BZMt7t4yqc8thWJA9n1++bnlWbV5Pe3WaSuDxst7/9xIhddR
  template:
    metadata:
      name: app-secret
      namespace: staging
    type: Opaque
