---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: staging
spec:
  encryptedData:
    REDIS_PASSWORD: AgAue7E+W7DVehe7nRo6UbZ4qejss5BlOU4gyhXAGBeVmiwgBuVE6HHs7uPiFUiFYyjEDQ2s8Dky0+JqoWVkMaXa8CCqtpb5vyhuD52lfweCdY+9L/AvGzoZI2IdBWn2foFZ75S3hHBYGh3vy1zOpku3C5XWM3cQvN2Rjq/oxg4RASfgc68KfwJFthdy8zWR+AdPJAtcZW59pV/FvYFCmArobcqMGodyu2iPDeegHw3iKkND/Yx9jEwF3PDWUaku7rIp8TiDwkD+dr4+HI8rJy4l9m4hjeiDC50gQO4TTI3TogGQHkJuzjh/xmjb5pNG9a0FsfoHr4Wxb+ySPvfOwDao7auEFUbmPij4+orHnocM0Crt59bDU+0/7lEFJmMBe+xQPPuSi69a7c4wN51dpIUdGpHLinhiRn2gpztNlhNsqTQlbPa+0xJVqkgKZPCob4SWvh3s7LKgWnP0BudgCr5IHsG51TRosKlzFxv6n2gsRThvfYPTgfhA9QSV0Mv11s1Rm7hnhKuPRjmQzuj/HLxd8IZLFP37Oq0RsMGo7Rmqk5ZOnqRgAvk5+Ly8cfzj32gx36DI1Kobk8EDBt3sP64B6LC0cNohui+oapaXbgbW0g3DDeYaxNh2ImVucLpfHFJ3ofec4MdbrG1m4RoAnD/+nm9hrLmJe0JNqP/oBzF3d4f1v9QwFaxLE8hQkvz8clk8ItooRmS5PRKJ
  template:
    metadata:
      name: app-secret
      namespace: staging
