---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: staging
spec:
  encryptedData:
    REDIS_PASSWORD: AgAmI0ZyjxotCcKztRfc+7gdbqoSOkWMBeNmGec5z5QEDNDyySVJXPsQaoj2NMqoiwforSorYouB1wY8O4AJAn+H+U0m2gEsCs+LSn2IoxrChVV1E72GALmDsTFiaKTcrXiB0yZYUKEXi0Wk7PGodcdBqI/olvk7OdyVm22hzcPHzXEuwp4OjXmq7Wv0id/hJTanudIWI1UqztoEgdqJmjYN82/tvDUYNJC8rJpOGpoILBYDcJgu3c4FJBhvMgQadX8YGK6vvkCf17cYBWE5CHoz7Ps0IQtOSoDomc4KQRL0i5grim2HKzis9jHJyocAyt+TQBGn+LMXIVO0VdZcyC0px/RI+qR2aeqFQZhRcCdiT3sqQfWFgdJdSpxkDgltmGUIo+8N/aXWEiqKl9NzDEUXgw5Mj2o1YDx+BTcSXuEO0vBtW21Ati12obZGbjIT/yJloVv7DHXpigDOwoD7DubW4rb6blhBa7CJL28XxK3fvKdFwIcK5AFhcRzqQRd81il+jk2Ty4XKr6B74QGNGRFy8PAdFH2FKEOR1CtVs8jjByCo3BBX2tiCKo4KYNoJSv2IhzQNxVzMnAUtkAmTzMYzeKV+gmQFB0e5cV+LUxj55hxjWExbolx46zv6pd5AefwR9BCHDAR3aB+kEg4Z/DGbEgw5KKLSlGMbr3UVVay7BV60ONBrfpOiAOR6BsrzJt5ELsIHucb2YOmoXJpYMw==
  template:
    metadata:
      name: app-secret
      namespace: staging
    type: Opaque
