apiVersion: v1
kind: Namespace
metadata:
  name: staging
  annotations:
    config.linkerd.io/proxy-cpu-limit: "200m"
    config.linkerd.io/proxy-cpu-request: "100m"
    config.linkerd.io/proxy-memory-limit: "256Mi"
    config.linkerd.io/proxy-memory-request: "128Mi"
  labels:
    name: staging
    environment: staging
    pod-security.kubernetes.io/enforce: privileged 
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted