---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: production
spec:
  encryptedData:
    REDIS_PASSWORD: AgBFxe+rLrdMnBdi0y0skWw/V/EMw/jgu/MoGALjzlCKc4POgExWkkIxP3W6jd04q2EaJJFbTi/OroI1IOD9S58QkqgS1PBJ4pIJbtTRSH/Z39oZS9Ww4WrbvQR01UL/Vp2Ajt1H5LqPC3a3EOvXvnpH5hMZtCwM+t+XSgRzAA9Sa/aPmqQmt4gexQfz4RgbZlVam8MBjO8yvOX6MVJ2bnZd0kJN24euqrjR0XnWV+B56JMeq53vSFdAj7Mc2CWGMY6YdpX4v8VDRXul1caRS0bbCt2/WMtWf1ZgDfr+YprPw314wRK8VBDNeR9YFlWe86bTymYSsM/auBgPxfXZNbXKhc20sCdmmvRgNwJI60DhEBrbULTWTqk8ojP04WThTVk+E+1wU9/JEPTA5fsQ8gJF7w4n3j5WoUo6C8jQAsg6yunOHW8+bVsE/75FEVugpUwy+wgfOLkzqiHBUJOJXBEbbHB8im0au51ZjR2hVd5LxKkIPJv1QZ+WRS4YDyz8c/4QV7SBk58vam/fuVqkMARFGXHmqlc6O5aZ6jImeq+tNnZ0yLh7wbXbQg60QRdgIOvc8LRXS0AGLRbz86g8dhaB6a7GR9rtiZcQ8JJz906TB0mfRXqdoMxDOwakPaz6GuUlr9jdQaoVb+NtIywD/wdYh4p5jQgpFe1dszDdo8ssAcMnTYrK1JQvZwhvQns/jN46Bc4FuvVr5hZvP2Pw
  template:
    metadata:
      name: app-secret
      namespace: production
    type: Opaque
